service: todo-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 30
  logRetentionInDays: 7
  tracing:
    lambda: true
  layers:
    - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-2-0:1
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler

package:
  individually: true

functions:
  get-todo-list:
    handler: src/handlers/get-todo-list/index.handler
    events:
      - http:
          path: /todo
          method: get

  post-todo:
    handler: src/handlers/post-todo/index.handler
    events:
      - http:
          path: /todo
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-prune-plugin
  
custom:
  esbuild:
    minify: false
    bundle: true
    sourcemap: true
    watch:
      pattern:
        ['src/**/*.ts']
      ignore: ['.serverless/**/*', '.build', '.esbuild']

  prune:
    automatic: true
    number: 3

