name: pub-web-dev-deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - web/pub/**

jobs:
  deploy:
    name: Pub Web dev deploy
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      stage: dev
      environment: dev
      working-directory: ./web/pub/
      tooling: node
      tooling-version: 16
      target-build: true
      target-lint: true
      target-unit-tests: true
      target-deploy: true
      AWS_DEFAULT_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

