name: random-generator-svc-dev-deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - services/random-generator-svc/**

jobs:
  deploy-service:
    name: Random Generator Service dev deploy
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      stage: dev
      environment: dev
      working-directory: ./services/random-generator-svc/
      tooling: node
      tooling-version: 16
      target-build: true
      target-lint: true
      target-unit-tests: true
      target-deploy: true
      AWS_DEFAULT_REGION: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-keys:
    runs-on: ubuntu-20.04
    steps:
      - uses: flaviostutz/aws-secrets-manager-action@main

